### ISSUE TITLE
nota bene

### ISSUE THREAD

**Issue by t81lal** [Jire/mango#1]
By calling this a "compiler", you are doing a disservice to the entire human race.

Good day.

**Comment by Jire** [comment]
What do u want me to do about it lel

**Comment by t81lal** [comment]
Public apology or seppoku.

**Comment by Jire** [comment]
This is the best compiler which compiles during compilation a set of code to be compiled.

**Comment by maaatts** [comment]
by closing this issue, you just assumed my gender and this triggers me greatly.

therefore i have no choice but to report you to the internet police, asshole.

**Comment by t81lal** [comment]
You have been warned.

**Comment by Jire** [comment]
Quasi-judicial impalement results in the airspeed of a fully laden swallow.
